default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^.*\.md$
      - id: end-of-file-fixer
      - id: debug-statements
      - id: mixed-line-ending
        args: [ --fix=lf ]
      - id: check-merge-conflict

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.4.7'
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        language: system
        entry: poetry
        types: [ python ]
        pass_filenames: false
        args:
          - run
          - pyright
          - "-p"
          - pyproject.toml

  - repo: https://github.com/crate-ci/typos
    rev: v1.25.0
    hooks:
      - id: typos
