hw_models:
  year:
    1968: "460"
    1969: "398"
    1970: "313"
    1971: "194"
    1972: "56"
    1973: "206"
    1974: "61"
    1975: "75"
    1976: "53"
    1977: "124"
    1978: "37"
    1979: "78"
    1980: "68"
    1981: "54"
    1982: "163"
    1983: "227"
    1984: "104"
    1985: "137"
    1986: "109"
    1987: "78"
    1988: "151"
    1989: "316"
    1990: "298"
    1991: "244"
    1992: "262"
    1993: "496"
    1994: "262"
    1995: "736"
    1996: "758"
    1997: "857"
    1998: "1238"
    1999: "1087"
    2000: "1329"
    2001: "1138"
    2002: "1248"
    2003: "1135"
    2004: "1325"
    2005: "1335"
    2006: "1582"
    2007: "1573"
    2008: "1555"
    2009: "1616"
    2010: "1700"
    2011: "1728"
    2012: "1487"
    2013: "1406"
    2014: "1457"
    2015: "1546"
    2016: "2232"
    2017: "2317"
    2018: "2260"
    2019: "2189"
    2020: "2156"
    2021: "2323"
    2022: "2408"
    2023: "2311"
    2024: "2118"
    2025: "282"

  query_params:
    query: "2025"
    _: "1734683238625"
    length: "5000"
    start: "0"
    draw: "1"
    columns[0][data]: "amount"
    columns[0][name]: ""
    columns[0][searchable]: "true"
    columns[0][orderable]: "true"
    columns[0][search][value]: ""
    columns[0][search][regex]: "false"
    columns[1][data]: "GalleryImage"
    columns[1][name]: ""
    columns[1][searchable]: "true"
    columns[1][orderable]: "false"
    columns[1][search][value]: ""
    columns[1][search][regex]: "false"
    columns[2][data]: "Col"
    columns[2][name]: ""
    columns[2][searchable]: "true"
    columns[2][orderable]: "true"
    columns[2][search][value]: ""
    columns[2][search][regex]: "false"
    columns[3][data]: "SeriesNum"
    columns[3][name]: ""
    columns[3][searchable]: "true"
    columns[3][orderable]: "true"
    columns[3][search][value]: ""
    columns[3][search][regex]: "false"
    columns[4][data]: "ModelName"
    columns[4][name]: ""
    columns[4][searchable]: "true"
    columns[4][orderable]: "true"
    columns[4][search][value]: ""
    columns[4][search][regex]: "false"
    columns[5][data]: "Year"
    columns[5][name]: ""
    columns[5][searchable]: "true"
    columns[5][orderable]: "true"
    columns[5][search][value]: ""
    columns[5][search][regex]: "false"
    columns[6][data]: "Series"
    columns[6][name]: ""
    columns[6][searchable]: "true"
    columns[6][orderable]: "true"
    columns[6][search][value]: ""
    columns[6][search][regex]: "false"
    columns[7][data]: "Color"
    columns[7][name]: ""
    columns[7][searchable]: "true"
    columns[7][orderable]: "true"
    columns[7][search][value]: ""
    columns[7][search][regex]: "false"
    columns[8][data]: "Tampo"
    columns[8][name]: ""
    columns[8][searchable]: "true"
    columns[8][orderable]: "true"
    columns[8][search][value]: ""
    columns[8][search][regex]: "false"
    columns[9][data]: "WheelType"
    columns[9][name]: ""
    columns[9][searchable]: "true"
    columns[9][orderable]: "true"
    columns[9][search][value]: ""
    columns[9][search][regex]: "false"
    columns[10][data]: "Toy"
    columns[10][name]: ""
    columns[10][searchable]: "true"
    columns[10][orderable]: "true"
    columns[10][search][value]: ""
    columns[10][search][regex]: "false"
    columns[11][data]: "AssortmentNum"
    columns[11][name]: ""
    columns[11][searchable]: "true"
    columns[11][orderable]: "true"
    columns[11][search][value]: ""
    columns[11][search][regex]: "false"
    columns[12][data]: "CaseNum"
    columns[12][name]: ""
    columns[12][searchable]: "true"
    columns[12][orderable]: "true"
    columns[12][search][value]: ""
    columns[12][search][regex]: "false"
    columns[13][data]: "Notes"
    columns[13][name]: ""
    columns[13][searchable]: "true"
    columns[13][orderable]: "true"
    columns[13][search][value]: ""
    columns[13][search][regex]: "false"
    columns[14][data]: ""
    columns[14][name]: ""
    columns[14][searchable]: "true"
    columns[14][orderable]: "false"
    columns[14][search][value]: ""
    columns[14][search][regex]: "false"
    columns[15][data]: "price"
    columns[15][name]: ""
    columns[15][searchable]: "true"
    columns[15][orderable]: "true"
    columns[15][search][value]: ""
    columns[15][search][regex]: "false"
    order[0][column]: "5"
    order[0][dir]: "desc"
    order[1][column]: "4"
    order[1][dir]: "asc"
    order[2][column]: "2"
    order[2][dir]: "asc"
    search[value]: ""
    search[regex]: "false"
