"""add users, models, modelusers and series tables

Revision ID: 7c41bf5f8596
Revises: 
Create Date: 2024-11-26 20:49:38.284567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlmodel.sql.sqltypes import AutoString


# revision identifiers, used by Alembic.
revision: str = '7c41bf5f8596'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', AutoString(), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('description', AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_name'), 'series', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', AutoString(), nullable=False),
    sa.Column('email', AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', AutoString(), nullable=False),
    sa.Column('category', sa.Enum('car', 'truck', 'motorcycle', 'plane', 'boat', name='modelcategory'), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Uuid(), nullable=True),
    sa.Column('description', AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=False)
    op.create_table('user_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('notes', AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('condition', sa.Enum('new', 'unpacked', 'slightly_damaged', 'damaged', name='modelcondition'), nullable=False),
    sa.Column('for_sale', sa.Boolean(), nullable=False),
    sa.Column('for_change', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_models_condition'), 'user_models', ['condition'], unique=False)
    op.create_index(op.f('ix_user_models_model_id'), 'user_models', ['model_id'], unique=False)
    op.create_index(op.f('ix_user_models_user_id'), 'user_models', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_models_user_id'), table_name='user_models')
    op.drop_index(op.f('ix_user_models_model_id'), table_name='user_models')
    op.drop_index(op.f('ix_user_models_condition'), table_name='user_models')
    op.drop_table('user_models')
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_series_name'), table_name='series')
    op.drop_table('series')
    # ### end Alembic commands ###
